# Generated by Django 2.2.5 on 2019-09-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_system', '0002_custom'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='items',
            table='items',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
